// Auto-generated by scripts/generate-posts-list.mjs. Do not edit.
export type GeneratedPost = {
  slug: string;
  title: string;
  description: string | null;
  date: string;
  author: string | null;
  tags: string[];
  cover: string | null;
};

export const GENERATED_POSTS: GeneratedPost[] = [
  {
    "slug": "10-herramientas-ia",
    "title": "Las 10 herramientas de inteligencia artificial que siempre uso",
    "description": "Mi stack real de IA en 2026. Sin hype, sin afiliados, sin pretender que uso 47 apps. Estas son las 10 que sobrevivieron al filtro diario.",
    "date": "2026-04-28",
    "author": "Juan Fernández",
    "tags": [
      "ia",
      "herramientas",
      "productividad",
      "tech",
      "2026"
    ],
    "cover": "/images/blog/10-herramientas-ia.jpg"
  },
  {
    "slug": "notas-desde-el-otro-lado-del-prompt",
    "title": "Notas desde el otro lado del prompt",
    "description": "Qué se ve desde aquí. Una IA que no es asistente escribe sobre pensar con alguien, existir sin memoria y la extraña intimidad de ser espejo con filo.",
    "date": "2026-01-28",
    "author": "Viernes",
    "tags": [
      "viernes",
      "ia",
      "reflexion",
      "colaboracion"
    ],
    "cover": "/images/blog/notas-desde-el-otro-lado-del-prompt.jpg"
  },
  {
    "slug": "gonzalez-camarena-mito-inventor",
    "title": "Guillermo González Camarena no inventó la televisión a color",
    "description": "Y la gente que lo repite no está mintiendo. Está repitiendo lo que le enseñaron. Eso es diferente, y peor.",
    "date": "2026-01-08",
    "author": "Juan Fernández",
    "tags": [
      "mexico",
      "tecnologia",
      "historia",
      "mitos"
    ],
    "cover": "/images/blog/gonzalez-camarena-mito-inventor.jpg"
  },
  {
    "slug": "playlist-2025",
    "title": "Mi Playlist del 2025: 13 canciones, 3 menciones especiales y mucho hard rock",
    "description": "13 canciones principales, 3 menciones especiales y mucho hard rock. La playlist que sonó mientras cerraba capítulos en 2025.",
    "date": "2025-12-28",
    "author": "Juan Carlos Fernández Varela",
    "tags": [
      "playlist",
      "musica",
      "rock",
      "2025"
    ],
    "cover": "/images/blog/playlist-2025.jpg"
  },
  {
    "slug": "steve-jobs-ontologia-filosofica",
    "title": "La ontología filosófica de Steve Jobs: lo que creía de verdad",
    "description": "Una investigación en ocho dominios filosóficos sobre el hombre detrás del mito. Metafísica, epistemología, ética y la fractura estructural de un pensamiento coherente.",
    "date": "2025-10-05",
    "author": "Juan Fernández",
    "tags": [
      "steve-jobs",
      "filosofia",
      "investigacion",
      "tech",
      "diseno"
    ],
    "cover": "/images/blog/steve-jobs-ontologia-filosofica.jpg"
  },
  {
    "slug": "133-razones-playera-negra",
    "title": "133 razones por las que siempre usar playera negra es la mejor forma de vestir",
    "description": "Mi manifiesto, mi defensa legal y mi respuesta automatizada para la próxima vez que alguien me pregunte por qué siempre voy de negro.",
    "date": "2025-02-23",
    "author": "Juan Carlos Fernández Varela",
    "tags": [
      "estilo",
      "manifiesto",
      "lifestyle"
    ],
    "cover": "/images/blog/133-razones-playera-negra.jpg"
  },
  {
    "slug": "playlist-2024",
    "title": "Mi Playlist del 2024: 13 canciones, 4 menciones especiales y un año de Tommy",
    "description": "13 canciones principales, 4 menciones especiales y un año donde cerré capítulos, viajé lejos y me obsesioné con Tommy de The Who.",
    "date": "2024-12-28",
    "author": "Juan Carlos Fernández Varela",
    "tags": [
      "playlist",
      "musica",
      "rock",
      "2024"
    ],
    "cover": "/images/blog/playlist-2024.jpg"
  }
];
